const scheduleEvents = [
  {
    date: '2026-04-01',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-02',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-03-03',
    time: '18:30',
    status: 'finished',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'TECH United',
    homeScore: 3,
    awayScore: 1,
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    date: '2026-03-13',
    time: '19:00',
    status: 'finished',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Innovation FC',
    homeScore: 2,
    awayScore: 0,
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    date: '2026-04-08',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-10',
    time: '18:30',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-12',
    time: '15:00',
    status: 'finished',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Code Warriors',
    homeScore: 3,
    awayScore: 1,
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    date: '2026-04-14',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-16',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-21',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-23',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-25',
    time: '18:30',
    status: 'finished',
    homeTeam: 'Digital FC',
    awayTeam: 'VR CONCEPT FC',
    homeScore: 2,
    awayScore: 1,
    location: 'Стадион «Авангард»',
    tournament: 'Чемпионат',
  },
  {
    date: '2026-04-28',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-04-30',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-06',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-08',
    time: '18:30',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-12',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-14',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-18',
    time: '19:00',
    status: 'upcoming',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Pixel FC',
    homeScore: null,
    awayScore: null,
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    date: '2026-05-20',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-22',
    time: '18:30',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-26',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-05-28',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-02',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-04',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-05',
    time: '18:30',
    status: 'upcoming',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Digital FC',
    homeScore: null,
    awayScore: null,
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    date: '2026-06-09',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-12',
    time: '18:30',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-16',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-18',
    time: '19:00',
    status: 'training',
    homeTeam: '',
    awayTeam: '',
    homeScore: null,
    awayScore: null,
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    date: '2026-06-19',
    time: '18:30',
    status: 'upcoming',
    homeTeam: 'Innovation FC',
    awayTeam: 'VR CONCEPT FC',
    homeScore: null,
    awayScore: null,
    location: 'Стадион «Авангард»',
    tournament: 'Чемпионат',
  },
];

export const migration002CreateAndSeedScheduleEvents = {
  name: '002_create_and_seed_schedule_events',

  up(db) {
    db.exec(`
      CREATE TABLE IF NOT EXISTS schedule_events (
        id INTEGER PRIMARY KEY AUTOINCREMENT,
        date TEXT NOT NULL,
        time TEXT NOT NULL,
        status TEXT NOT NULL CHECK(status IN ('upcoming', 'finished', 'training')),
        home_team TEXT DEFAULT '',
        away_team TEXT DEFAULT '',
        home_score INTEGER DEFAULT NULL,
        away_score INTEGER DEFAULT NULL,
        location TEXT NOT NULL,
        tournament TEXT NOT NULL
      );

      CREATE INDEX IF NOT EXISTS idx_schedule_events_datetime
      ON schedule_events(date, time);
    `);

    const existingEvents = db
      .prepare('SELECT COUNT(*) as count FROM schedule_events')
      .get();

    if (existingEvents.count > 0) {
      return;
    }

    const insertEvent = db.prepare(`
      INSERT INTO schedule_events (
        date,
        time,
        status,
        home_team,
        away_team,
        home_score,
        away_score,
        location,
        tournament
      )
      VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?)
    `);

    for (const event of scheduleEvents) {
      insertEvent.run(
        event.date,
        event.time,
        event.status,
        event.homeTeam,
        event.awayTeam,
        event.homeScore,
        event.awayScore,
        event.location,
        event.tournament,
      );
    }
  },
};
