import type { ScheduleEvent, StatusFilter } from './types';

export const scheduleEvents: ScheduleEvent[] = [
  {
    id: 1,
    date: '2026-04-01',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 2,
    date: '2026-04-02',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 3,
    date: '2026-03-03',
    time: '18:30',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'TECH United',
    homeScore: 3,
    awayScore: 1,
    status: 'finished',
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    id: 4,
    date: '2026-03-13',
    time: '19:00',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Innovation FC',
    homeScore: 2,
    awayScore: 0,
    status: 'finished',
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    id: 5,
    date: '2026-04-08',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 6,
    date: '2026-04-10',
    time: '18:30',
    status: 'training',
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    id: 7,
    date: '2026-04-12',
    time: '15:00',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Code Warriors',
    homeScore: 3,
    awayScore: 1,
    status: 'finished',
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    id: 8,
    date: '2026-04-14',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 9,
    date: '2026-04-16',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 10,
    date: '2026-04-25',
    time: '18:30',
    homeTeam: 'Digital FC',
    awayTeam: 'VR CONCEPT FC',
    homeScore: 2,
    awayScore: 1,
    status: 'finished',
    location: 'Стадион «Авангард»',
    tournament: 'Чемпионат',
  },
  {
    id: 11,
    date: '2026-04-21',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 12,
    date: '2026-04-23',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    id: 13,
    date: '2026-04-28',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 14,
    date: '2026-04-30',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 15,
    date: '2026-05-06',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 16,
    date: '2026-05-08',
    time: '18:30',
    status: 'training',
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    id: 17,
    date: '2026-05-12',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 18,
    date: '2026-05-14',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 19,
    date: '2026-05-18',
    time: '19:00',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Pixel FC',
    status: 'upcoming',
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    id: 20,
    date: '2026-05-20',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 21,
    date: '2026-05-22',
    time: '18:30',
    status: 'training',
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    id: 22,
    date: '2026-05-26',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 23,
    date: '2026-05-28',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 24,
    date: '2026-06-02',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 25,
    date: '2026-06-04',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 26,
    date: '2026-06-05',
    time: '18:30',
    homeTeam: 'VR CONCEPT FC',
    awayTeam: 'Digital FC',
    status: 'upcoming',
    location: 'Стадион «Луч»',
    tournament: 'Чемпионат',
  },
  {
    id: 27,
    date: '2026-06-09',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 28,
    date: '2026-06-12',
    time: '18:30',
    status: 'training',
    location: 'Тренировочное поле №2',
    tournament: 'Тренировка',
  },
  {
    id: 29,
    date: '2026-06-16',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 30,
    date: '2026-06-18',
    time: '19:00',
    status: 'training',
    location: 'Тренировочное поле',
    tournament: 'Тренировка',
  },
  {
    id: 31,
    date: '2026-06-19',
    time: '18:30',
    homeTeam: 'Innovation FC',
    awayTeam: 'VR CONCEPT FC',
    status: 'upcoming',
    location: 'Стадион «Авангард»',
    tournament: 'Чемпионат',
  },
];

export const scheduleFilters: Array<{
  value: StatusFilter;
  label: string;
}> = [
  {
    value: 'all',
    label: 'Все',
  },
  {
    value: 'upcoming',
    label: 'Предстоящие',
  },
  {
    value: 'finished',
    label: 'Завершенные',
  },
  {
    value: 'training',
    label: 'Тренировки',
  },
];
